### ISSUE TITLE
Allow same key in keystroke

### ISSUE THREAD

**Issue by zhaocai** [t9md/atom-keystroke#1]
## Objective: Search for visually selected text

In Vim, we can use `vnoremap // y/<C-R>"<CR>`
## Config in atom-vim-mode-plus,

``` cson
{
    name: "visual-search"
    keystroke: "y g v / shift-insert"
    scope: "atom-text-editor.vim-mode-plus.visual-mode"
}
```

``` cson
'atom-text-editor.vim-mode-plus.visual-mode':
  '/': 'keystroke:visual-search'
```
## Issue

Atom freeze because `/` key is repeating itself

**Comment by t9md** [comment]
What's the `shift-insert` part? Does this keystroke normally do?
I want to confirm the purpose of what this definition of keystroke do in short sentence.

**Comment by zhaocai** [comment]
`shift-insert` is `paste` in windows (like `cmd+v` in mac). (`ctrl-v` is the default key for paste in windows but it is taken by other purpose in `vim-mode-plus`)

**Comment by t9md** [comment]
OK, thanks.
