### ISSUE TITLE
`i` to enter insert mode is not working

### ISSUE THREAD

**Issue by zhaocai** [t9md/atom-keystroke#2]
The following keystroke intends to insert white-space without leaving normal-mode. But it is not working. I guess it is related to `i` to enter insert mode.

``` cson
'atom-text-editor.vim-mode-plus.normal-mode':
  'shift-space': 'keystroke:insert-space'
```

``` cson
{
  name: "insert-space"
  keystroke: "i space escape l"
  scope: "atom-text-editor.vim-mode-plus.normal-mode"
}
```

**Comment by t9md** [comment]
Basically you can not use key which is not directly mapped to some command(like `space` in `insert-mode` which directly insert text).

I don't know it's technically fixable or not.

**Comment by zhaocai** [comment]
Thanks for the info.

**Comment by zhaocai** [comment]
## Issue in one sentence

How to reset/remove the hovering pending count with a function or command?

## Objective

Insert `activeVimState.getCount()` whitespaces without leaving normal mode. 

``` coffeescript
### init.coffee 
# same code from your dotfiles
getActiveVimState = ->
  getEditorState(getEditor())
###

insertWhitespace = ->
  return unless editor = atom.workspace.getActiveTextEditor()
  v = getActiveVimState()
  space = ' '
  if v.hasCount()
    space = Array(v.getCount() + 1).join space
    atom.commands.dispatch('atom-text-editor.vim-mode-plus', 'vim-mode-plus:reset-normal-mode')
  editor.insertText(space)
```

## Problem

Can not find a way to reset/remove the hovering pending count. 

![pending-count](https://dl.dropboxusercontent.com/u/1897501/Screencasts/atom-vim-insert-whitespace.gif) 

### Tested Methods
-   dispatch `'vim-mode-plus:reset-normal-mode'` command

**Comment by t9md** [comment]
Havent't investigated yet, from what you want to do. Itms straight forward to create operator to insert space which take number of spaces from count you specify.
Vmp's wiki section have instruction for vmp plugin.

**Comment by t9md** [comment]
this is example

https://github.com/t9md/atom-vim-mode-plus/wiki/Extend-vmp-in-init-file#basic-insertspaces-operator-which-insert-specified-count-of-spaces

**Comment by zhaocai** [comment]
Thank you 😀 That is extremely helpful.
